SRC_DATA_DIR_NAME = datafiles
SRC_DATA_DIR = $$PROJECT_TOP_SRCDIR/$$SRC_DATA_DIR_NAME
DEST_DATA_DIR_NAME = $${TARGET}-data
DEST_DATA_DIR = $$DESTDIR/$$DEST_DATA_DIR_NAME

include ($$PWD/datafiles.pri)
