CONFIG += c++14
CONFIG+=hide_symbols

win32: LIB_DIR_NAME = bin
else:  LIB_DIR_NAME = lib

QF_PROJECT_TOP_SRCDIR = $$PWD
QF_PROJECT_TOP_BUILDDIR = $$shadowed($$QF_PROJECT_TOP_SRCDIR)

LIBS_DIR = $$QF_PROJECT_TOP_BUILDDIR/$$LIB_DIR_NAME
