#ifndef QFSQLFIELDINFO_H
#define QFSQLFIELDINFO_H

#include <QSqlField>

class QFSqlFieldInfo : public QSqlField
{
private:
	struct Data
	{
		QString fulltablename;
		QString seqname;
		quint8 nullable:1, isunsigned:1, autoincrement:1;
		QString characterSet;
		QString collation;
		QString comment;
		QVariantMap nativeValues;
		Data(const QString& full_tbl_name)
			: fulltablename(full_tbl_name), nullable(true), isunsigned(false), autoincrement(false) {}
	};
	Data data;
public:
	//! \a fullName always starts with '.'
	QString fullName() const {return data.fulltablename + '.' + name();}
	//bool isValid() const {return QSqlField::isValid();}
	QString seqName() const {return data.seqname;} //!< name of sequence, if field is autogenerated
	void setSeqName(const QString &n) {data.seqname = n;}
	const QVariantMap& nativeValues() const {return data.nativeValues;}
	QVariant nativeValue(const QString &key) const {return nativeValues().value(key);}
	QVariantMap& nativeValuesRef() {return data.nativeValues;}
	QStringList enumOrSetFields() const {return nativeValue("enumOrSetFields").toStringList();}
	QString nativeType() const {return data.nativeValues.value("nativeType").toString();}
	void setNativeType(const QString &s) {data.nativeValues["nativeType"] = s;}
	QString characterSet() const {return data.characterSet;}
	void setCharacterSet(const QString &s) {data.characterSet = s;}
	QString collation() const {return data.collation;}
	void setCollation(const QString &s) {data.collation = s;}
	QString comment() const {return data.comment;}
	void setComment(const QString &s) {data.comment = s;}
	bool isNullable() const {return data.nullable;}
	void setNullable(bool b) {data.nullable = b;}
	bool isUnsigned() const {return data.isunsigned;}
	void setUnsigned(bool b) {data.isunsigned = b;}
	bool isAutoIncrement() const {return data.autoincrement;}
	void setAutoIncrement(bool b) {data.autoincrement = b;}
	QVariant seqNextVal();
	QString toString(const QString &indent = QString()) const;

	static QList<QFSqlFieldInfo> loadFields(const QSqlDatabase &connection, const QString table_id);

public:
	QFSqlFieldInfo(const QString& full_tbl_name = QString())
		: QSqlField(), data(full_tbl_name)
	{
	}
};

struct QFSqlIndexInfo
{
	QString name;
	bool unique;
	bool primary;
	QStringList fields;

	QFSqlIndexInfo() : unique(false), primary(false) {}

	static QList<QFSqlIndexInfo> loadIndexes(const QSqlDatabase &connection, const QString table_id);
};

#endif // QFSQLFIELDINFO_H
