#ifndef QF_CORE_QML_PLUGIN_GLOBAL_H
#define QF_CORE_QML_PLUGIN_GLOBAL_H

#include <qglobal.h>

#if defined(QF_CORE_QML_PLUGIN_BUILD_DLL)
//#warning "EXPORT"
#  define QF_CORE_QML_PLUGIN_DECL_EXPORT Q_DECL_EXPORT
#else
//#warning "IMPORT"
#  define QF_CORE_QML_PLUGIN_DECL_EXPORT Q_DECL_IMPORT
#endif

#endif // QF_CORE_QML_PLUGIN_GLOBAL_H
