#! /usr/bin/dh-exec
lib/qml/quickevent /usr/lib/x86_64-linux-gnu/qt5/lib/qml
lib/libquickeventcore.so.1 /usr/lib/${DEB_HOST_MULTIARCH}/
lib/libquickeventcore.so.1.0 /usr/lib/${DEB_HOST_MULTIARCH}/
lib/libquickeventcore.so.1.0.0 /usr/lib/${DEB_HOST_MULTIARCH}/
lib/libquickeventgui.so.1 /usr/lib/${DEB_HOST_MULTIARCH}/
lib/libquickeventgui.so.1.0 /usr/lib/${DEB_HOST_MULTIARCH}/
lib/libquickeventgui.so.1.0.0 /usr/lib/${DEB_HOST_MULTIARCH}/
