name: Setup CMake
description: "Invoke CMake and generate build files"
inputs:
  qt_version:
    description: "Specify Qt version to use"
    required: true
    default: "6.5.3"
  qt_arch:
    description: "Specify Qt arch to use"
    default: "gcc_64"
  use_qt6:
    description: "Specify whether we're using Qt 5 or Qt 6"
    required: true
  modules:
    description: "Specify which modules should be installed"
    required: true
  additional_cmake_args:
    description: "Additional args to pass to CMake"
    default: ""

runs:
  using: "composite"
  steps:
    # Linux deps
    - name: Install apt packages
      if: runner.os != 'Windows'
      uses: awalsh128/cache-apt-pkgs-action@v1.4.2
      with:
        packages: libgl1-mesa-dev libpulse-dev libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-util1 libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor-dev clazy libfuse-dev
        version: 1.0

    # Windows deps
    - name: Install windows deps
      if: runner.os == 'Windows'
      run: |
        vcpkg install doctest:x64-mingw-dynamic trompeloeil:x64-mingw-dynamic
        echo cmake_extra_args="'-DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake' '-DMINGW=ON' '-G MinGW Makefiles'" >> "$GITHUB_ENV"
      shell: bash

    # Qt
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        cache: true
        version: ${{ inputs.qt_version }}
        arch: ${{ inputs.qt_arch }}
        install-deps: false
        modules: ${{ inputs.modules }}
        extra: --autodesktop

    - name: WASM-specific stuff
      if: inputs.qt_arch == 'wasm_singlethread'
      run: |
        chmod +x "${Qt6_DIR}/bin/qt-cmake"
        echo cmake_extra_args="'-DBUILD_SHARED_LIBS=OFF' '-DQT_HOST_PATH=$(realpath "${Qt6_DIR}/../gcc_64")'" >> "$GITHUB_ENV"
        echo CMAKE_BIN="${Qt6_DIR}/bin/qt-cmake" >> "$GITHUB_ENV"
      shell: bash

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1.2.12
      with:
        key: ${{ github.job }}

    - name: Configure CMake
      run: |
        # CFLAGS="-Werror ${CFLAGS}" \
        # CXXFLAGS="-Werror ${CXXFLAGS}" \
        "${CMAKE_BIN:-cmake}" \
          -S '${{github.workspace}}' \
          -B '${{github.workspace}}/build' \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=OFF \
          -DCMAKE_C_COMPILER_LAUNCHER=ccache \
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DUSE_QT6=${{ inputs.use_qt6 }} \
          ${{ env.cmake_extra_args }} \
          ${{ inputs.additional_cmake_args }}
      shell: bash
